server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: bank
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    fallback-to-system-locale: false

jwt:
  access-token-expiration-time-ms: 604800000
  refresh-token-expiration-time-ms: 604800000
  secret-key: 2B4B7DDEA1E27A9ACEBC6E2CD4877

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
